---
name: Beautiful Jekyll CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          # runs `bundle install` and caches gems automatically,
          # unfortunately the `Build site` step fails when using cache
          # bundler-cache: true

      - name: Install ruby dependencies
        run: |
          bundle install
          bundle exec appraisal install

      - name: Build site
        run: |
          bundle exec appraisal jekyll build --future

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site/
          if-no-files-found: error

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: _site
          path: gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
